### PR TITLE
Trigger update for publish and unpublish

### PR DESCRIPTION
**Pull request by cameronbourgeois**

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow how do we feel about this PR? Do we want to get it in. Is it still a  problem that unpublished content remains in the index?

**Comment by tractorcow** [comment]
Missing check for `$this->owner->ID` being empty. It would be good if there were unit tests to show what this actually fixed.

**Comment by tractorcow** [comment]
Closed in favour of https://github.com/silverstripe/silverstripe-fulltextsearch/pull/137#issuecomment-284604644, which fixes the issue a bit more directly. :)

**Comment by tractorcow** [comment]
I repent. This PR actually introduces the necessary onAfter* hooks for catching item deletes.

**Comment by tractorcow** [comment]
Apparently, this code is preventing delete manipulations being processed.

```
// Trim records without fields
        foreach(array_keys($writes) as $key) {
            if(empty($writes[$key]['fields'])) {
                unset($writes[$key]);
            }
        }
```

Because deletes don't have a fields key.

**Comment by tractorcow** [comment]
Replaced with https://github.com/silverstripe/silverstripe-fulltextsearch/pull/138

**Pull request closed without merging**
