### PR TITLE
adding ability to define different port for WebDAV than used for Solr

### PR DESCRIPTION
**Pull request by Lightnicus**
as discussed in issue #125

### CODE REVIEW

**Comment by dhensby** [comment]
Can you add some docs about usage, please?

**Comment by Lightnicus** [comment]
@dhensby I extended the comment on the Solr class that describes usage of the config arrays (see changes). Would you like me to add something to a documentation file as well?

**Comment by dhensby** [comment]
Yes please

**Comment by Lightnicus** [comment]
@dhensby I've added a section with example configuration that includes all possible parameters in the documentation, with commentary

**Comment by dhensby** [comment]
Thanks

**Pull request merged**
