### PR TITLE
Remove client-side commit, remove solr3 support, update thirdparty dependency

### PR DESCRIPTION
**Pull request by mateusz**
Below description of performed tests.

## Setup

One index was created (MysiteIndex):
```php
class MysiteIndex extends SolrIndex {
    function init() {
        $this->addClass('SiteTree');
        $this->addAllFulltextFields();
    }
}
```

A simple controller handler was created to query results:
```php
public function search() {
	$query = new SearchQuery();
	$query->search('test phrase');
	$results = singleton('MysiteIndex')->search($query);
	var_dump($results->Matches->First()->Title);
	exit;
}
```

## Testing scenario

- wipe index
- trigger Solr_Configure task
- trigger Solr_Reindex task
- trigger queuedjob if needed, await auto-commit
- perform search, confirm results come through
- update page
- trigger queuedjob if needed, await auto-commit
- perform search, confirm results come through

## Tested environments

- silverstripe-installer + fulltextsearch + fulltextsearch-local
- silverstripe-installer + fulltextsearch + queuedjobs + fulltextsearch-local
- cwp-installer (fulltextsearch + doorman + queuedjobs) + fulltextsearch-local
- cwp-installer on CWP (fulltextsearch + doorman + queuedjobs) + CWP's Solr4 service

### CODE REVIEW

**Comment by tractorcow** [comment]
I think the direction these changes are making is fine, but I'd like to spend some time testing. I'd also like to see some updated user-docs on how commits work, so that we don't need to re-read the code to understand how it's intended to work. :)

**Comment by tractorcow** [comment]
Green is good. I'd like to merge this once we get the 1.5.0 recipe out of the way though, if that's ok, to minimise our risk. ;)

**Comment by robbieaverill** [comment]
FYI the master branch (SS4) compatible now uses the Solr client via composer which this PR also includes it.

For SS3 we should use the 2.x release line, but if this is a breaking change it might not make it into SS3 any more I suppose.

**Comment by robbieaverill** [comment]
Feel free to revisit this if you'd like to @mateusz - thanks for contributing =)

**Comment by mateusz** [comment]
lol

**Pull request closed without merging**
