### PR TITLE
clean up SearchQuery API

### PR DESCRIPTION
**Pull request by andrewandante**
Updated port of https://github.com/silverstripe/silverstripe-fulltextsearch/pull/64/ to improve readability and usability of the `SearchQuery` API.

### CODE REVIEW

**Comment by NightJar** [comment]
Agree with docs request, otherwise I'd be green buttoning now :>

**Comment by andrewandante** [comment]
Totally agree, will update today

**Comment by andrewandante** [comment]
Have updated the ones I found @dhensby @NightJar 🔎

**Comment by NightJar** [comment]
Nice!

**Pull request merged**
