### PR TITLE
Add ContentControllerExtension back

### LINKED ISSUE #231: ContentControllerExtension not used in 3.4.0
I've noticed in 3.4.0 that `SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension` is no longer used.

Stumbled across with this coming from 3.3.1. 

Initially added in 7b78a841b015e1baa5f86404c0d88e81256dbf77 and removed in e08731d1f1b783f8202f283d85bdb4d5d4d8b720 which is included in the 3.4.0 tag.

I notice there is a related TODO mentioning to update docs once #216 was merged so perhaps it was forgotten about.

### PR DESCRIPTION
**Pull request by thats4shaw**
Fixes #231.

Initially added in 7b78a84 and removed in e08731d but was intended to be added back in once #216 was merged from what I can tell.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Do we want this in a patch release maybe?

**Comment by NightJar** [comment]
@thats4shaw I see your thumbs up - to get this into a patch release, please target the PR at the most specific branch that is relevant for this commit.

E.g.
- `master` will be the next _major_ release (N.0.0)
- `2` will be the next _minor_ release (2.N.0)
- `2.0` will be the next _patch_ release (2.0.N)

\* Numbers are examples, I didn't check actual setup ;)

**Comment by thats4shaw** [comment]
@NightJar I was a bit fuzzy on what branch to target since there is no 3.4 branch for this hence just targeting master. 

3.3 would be the closest but that already uses the extension.

**Comment by NightJar** [comment]
🤔 A 3.4 release with no 3.4 branch?

https://github.com/silverstripe/silverstripe-fulltextsearch/blob/7ee362a5c7b572da550c6292388c7362b784fc9a/composer.json#L46

Master is currently targeted at `3.5.0`

... BRB ...

**Comment by NightJar** [comment]
OK cool, I've merged up 3.3 into master, which is actually effectively 3.4.Next at the moment (there are no API changes or feature adds) - so I'll merge your PR, and we can worry about the 3.4 branch after :)

**Comment by thats4shaw** [comment]
Thanks @NightJar!

**Comment by ScopeyNZ** [comment]
This will be released in 3.6.0 shortly - sorry about the delay on this one @thats4shaw - fell off the radar! 🙈

**Pull request merged**
