### PR TITLE
FIX #108 - Update and simplify getDirtyIDs method

### LINKED ISSUE #108: singleton($step['class'])->extend('augmentSQL', $sql); in SearchIndex::getDirtyIDs() causes throwing Fatal Errors
`singleton($step['class'])->extend('augmentSQL', $sql);` in `SearchIndex::getDirtyIDs()` function breaks some `DataExtension` objects when calling to their function augmentSQL(), eg. Translatable, or SiteTreeSubsites, since `Translatable::augumentSQL(SQLQuery &$query, DataQuery &$dataQuery = null)` is expecting the second parameter is a `DataQuery` object and directly uses it to call its function `getQueryParam()` in its implementation without checking if $dataQuery is a non-object or not

So this issue could be either fixed in Translatable class or SearchIndex class. Giving that if we fix here in SearchIndex, non of those DataExtension classes need to do anything, I hope it could fixed here.

### PR DESCRIPTION
**Pull request by michalkleiner**
A follow-up PR to replace #239. The tests are now green and I will test it in our project.

Thanks for the pointers @UndefinedOffset and @tractorcow!

### CODE REVIEW

**Comment by dhensby** [comment]
I'd rather get #280 merged and then merge up than have these 2 PRs that will conflict when we try to merge up

**Comment by michalkleiner** [comment]
Whichever way is best. They are exactly the same, so yep, can be done that way. Potentially they wouldn't even conflict 🤷.

**Comment by dhensby** [comment]
OK - I've merged up - I'm surprised that we don't see a conflict with this PR, though

**Comment by michalkleiner** [comment]
I'd expect this PR now showing no changes, but perhaps I'd need to rebase and only after that it would show no changes.

**Pull request merged**
